import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateContactColumnNames1750973357843 implements MigrationInterface {
    name = 'UpdateContactColumnNames1750973357843'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."contact_name_trgm_idx"`);
        await queryRunner.query(`DROP INDEX "public"."contact_email_trgm_idx"`);
        await queryRunner.query(`DROP INDEX "public"."contact_company_trgm_idx"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd3f156a6ad8ae9b1a813dc561"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_454994be53ff3cf64ab0592677"`);
        await queryRunner.query(`DROP INDEX "public"."contact_search_vector_idx"`);
        await queryRunner.query(`CREATE TABLE "segment_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contact_id" character varying NOT NULL, "segment_id" uuid NOT NULL, "is_dynamic" boolean NOT NULL DEFAULT false, "added_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f3ec6efefc7892dbcebc1a42ac4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c7aa23c066b01af74449a644c" ON "segment_members" ("contact_id", "segment_id") `);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "brandId"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "crmListId"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "isCompany"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "isTracked"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "lastInteractionAt"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "relatedFrom"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "companyRole"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "contractValue"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "contractCurrency"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "emailBounceScore"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedInName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedInProviderId"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedInCompanyUrl"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "facebookName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "youtubeName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "instagramName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "telegramName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "whatsappName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "xName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "xCompanyName"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "websiteUrl"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedInMeta"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "brand_id" uuid`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "crm_list_id" character varying array DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "is_company" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "last_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "is_tracked" boolean`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "last_interaction_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "related_from" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "company_role" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "contract_value" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "contract_currency" character varying DEFAULT '$'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "email_bounce_score" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedin_name" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedin_provider_id" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedin_company_url" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "facebook_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "youtube_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "instagram_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "telegram_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "whatsapp_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "x_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "x_company_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "website_url" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedin_meta" jsonb DEFAULT '{}'`);
        await queryRunner.query(`CREATE INDEX "IDX_fb620010a66777527f157a4b79" ON "contacts" ("brand_id", "crm_list_id", "owners") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d42c1ab08ad3c048776bdda2f9" ON "contacts" ("brand_id", "crm_list_id", "email") `);
        await queryRunner.query(`ALTER TABLE "segment_members" ADD CONSTRAINT "FK_017c61b1015accf182fcc608928" FOREIGN KEY ("segment_id") REFERENCES "segments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "segment_members" DROP CONSTRAINT "FK_017c61b1015accf182fcc608928"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d42c1ab08ad3c048776bdda2f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb620010a66777527f157a4b79"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedin_meta"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "website_url"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "x_company_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "x_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "whatsapp_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "telegram_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "instagram_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "youtube_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "facebook_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedin_company_url"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedin_provider_id"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "linkedin_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "email_bounce_score"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "contract_currency"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "contract_value"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "company_role"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "related_from"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "last_interaction_at"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "is_tracked"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "is_company"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "crm_list_id"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "brand_id"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedInMeta" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "websiteUrl" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "xCompanyName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "xName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "whatsappName" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "telegramName" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "instagramName" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "youtubeName" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "facebookName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedInCompanyUrl" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedInProviderId" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "linkedInName" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "emailBounceScore" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "contractCurrency" character varying DEFAULT '$'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "contractValue" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "companyRole" character varying`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "relatedFrom" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "lastInteractionAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "isTracked" boolean`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "lastName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "isCompany" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "crmListId" character varying array DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "brandId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c7aa23c066b01af74449a644c"`);
        await queryRunner.query(`DROP TABLE "segment_members"`);
        await queryRunner.query(`CREATE INDEX "contact_search_vector_idx" ON "contacts" ("search_vector") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_454994be53ff3cf64ab0592677" ON "contacts" ("email", "brandId", "crmListId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd3f156a6ad8ae9b1a813dc561" ON "contacts" ("brandId", "crmListId", "owners") `);
        await queryRunner.query(`CREATE INDEX "contact_company_trgm_idx" ON "contacts" ("company") `);
        await queryRunner.query(`CREATE INDEX "contact_email_trgm_idx" ON "contacts" ("email") `);
        await queryRunner.query(`CREATE INDEX "contact_name_trgm_idx" ON "contacts" ("name") `);
    }

}
